import type { DeviceDataProvider, RawDeviceRecord } from '../schema/raw.js';

/**
 * Android device geometry.
 *
 * Physical resolution and display density come from manufacturer product
 * specifications. Window-inset behaviour (status bar, gesture navigation,
 * display cutouts, density buckets) follows the Android developer
 * documentation on WindowInsets and DisplayCutout.
 *
 * Android insets are genuinely device- and OEM-skin-dependent and can change
 * with an OS update, so every inset here is carried at `medium` confidence
 * with an explicit caveat rather than being presented as exact.
 */

const ANDROID_CONVENTIONS = {
  minTouchTarget: 48,
  defaultScreenMargin: 16,
  bottomTabBarHeight: 80,
  systemFont: 'Roboto',
} as const;

interface AndroidSpec {
  id: string;
  manufacturer: string;
  family: string;
  model: string;
  marketingName: string;
  osMin: string;
  year: number;
  generation: string;
  inches: number;
  logical: [number, number];
  physical: [number, number];
  dpr: number;
  ppi: number;
  bucket: string;
  statusBar: number;
  /** Bottom inset with gesture navigation enabled. */
  gestureInset: number;
  cutout: RawDeviceRecord['cutoutKind'];
  cutoutBox: [number, number, number];
  cornerRadius: number;
  keyboardHeight: number;
}

const PHONES: AndroidSpec[] = [
  {
    id: 'google-pixel-5',
    manufacturer: 'Google',
    family: 'Pixel',
    model: 'Pixel 5',
    marketingName: 'Google Pixel 5',
    osMin: '11',
    year: 2020,
    generation: '5',
    inches: 6.0,
    logical: [393, 851],
    physical: [1080, 2340],
    dpr: 2.75,
    ppi: 432,
    bucket: 'xxhdpi',
    statusBar: 24,
    gestureInset: 24,
    cutout: 'punch-hole-left',
    cutoutBox: [24, 24, 12],
    cornerRadius: 20,
    keyboardHeight: 260,
  },
  {
    id: 'google-pixel-6',
    manufacturer: 'Google',
    family: 'Pixel',
    model: 'Pixel 6',
    marketingName: 'Google Pixel 6',
    osMin: '12',
    year: 2021,
    generation: '6',
    inches: 6.4,
    logical: [412, 915],
    physical: [1080, 2400],
    dpr: 2.625,
    ppi: 411,
    bucket: 'xxhdpi',
    statusBar: 24,
    gestureInset: 24,
    cutout: 'punch-hole-center',
    cutoutBox: [26, 26, 10],
    cornerRadius: 24,
    keyboardHeight: 270,
  },
  {
    id: 'google-pixel-7',
    manufacturer: 'Google',
    family: 'Pixel',
    model: 'Pixel 7',
    marketingName: 'Google Pixel 7',
    osMin: '13',
    year: 2022,
    generation: '7',
    inches: 6.3,
    logical: [412, 915],
    physical: [1080, 2400],
    dpr: 2.625,
    ppi: 416,
    bucket: 'xxhdpi',
    statusBar: 24,
    gestureInset: 24,
    cutout: 'punch-hole-center',
    cutoutBox: [26, 26, 10],
    cornerRadius: 24,
    keyboardHeight: 270,
  },
  {
    id: 'google-pixel-7-pro',
    manufacturer: 'Google',
    family: 'Pixel',
    model: 'Pixel 7 Pro',
    marketingName: 'Google Pixel 7 Pro',
    osMin: '13',
    year: 2022,
    generation: '7',
    inches: 6.7,
    logical: [412, 892],
    physical: [1440, 3120],
    dpr: 3.5,
    ppi: 512,
    bucket: 'xxxhdpi',
    statusBar: 24,
    gestureInset: 24,
    cutout: 'punch-hole-center',
    cutoutBox: [26, 26, 10],
    cornerRadius: 28,
    keyboardHeight: 270,
  },
  {
    id: 'google-pixel-8',
    manufacturer: 'Google',
    family: 'Pixel',
    model: 'Pixel 8',
    marketingName: 'Google Pixel 8',
    osMin: '14',
    year: 2023,
    generation: '8',
    inches: 6.2,
    logical: [412, 915],
    physical: [1080, 2400],
    dpr: 2.625,
    ppi: 428,
    bucket: 'xxhdpi',
    statusBar: 24,
    gestureInset: 24,
    cutout: 'punch-hole-center',
    cutoutBox: [26, 26, 10],
    cornerRadius: 24,
    keyboardHeight: 270,
  },
  {
    id: 'google-pixel-8-pro',
    manufacturer: 'Google',
    family: 'Pixel',
    model: 'Pixel 8 Pro',
    marketingName: 'Google Pixel 8 Pro',
    osMin: '14',
    year: 2023,
    generation: '8',
    inches: 6.7,
    logical: [448, 997],
    physical: [1344, 2992],
    dpr: 3,
    ppi: 489,
    bucket: 'xxxhdpi',
    statusBar: 24,
    gestureInset: 24,
    cutout: 'punch-hole-center',
    cutoutBox: [26, 26, 10],
    cornerRadius: 28,
    keyboardHeight: 280,
  },
  {
    id: 'google-pixel-9',
    manufacturer: 'Google',
    family: 'Pixel',
    model: 'Pixel 9',
    marketingName: 'Google Pixel 9',
    osMin: '14',
    year: 2024,
    generation: '9',
    inches: 6.3,
    logical: [411, 923],
    physical: [1080, 2424],
    dpr: 2.625,
    ppi: 422,
    bucket: 'xxhdpi',
    statusBar: 24,
    gestureInset: 24,
    cutout: 'punch-hole-center',
    cutoutBox: [26, 26, 10],
    cornerRadius: 26,
    keyboardHeight: 275,
  },
  {
    id: 'google-pixel-9-pro-xl',
    manufacturer: 'Google',
    family: 'Pixel',
    model: 'Pixel 9 Pro XL',
    marketingName: 'Google Pixel 9 Pro XL',
    osMin: '14',
    year: 2024,
    generation: '9',
    inches: 6.8,
    logical: [427, 950],
    physical: [1344, 2992],
    dpr: 3.15,
    ppi: 486,
    bucket: 'xxxhdpi',
    statusBar: 24,
    gestureInset: 24,
    cutout: 'punch-hole-center',
    cutoutBox: [26, 26, 10],
    cornerRadius: 28,
    keyboardHeight: 285,
  },
  {
    id: 'samsung-galaxy-s21',
    manufacturer: 'Samsung',
    family: 'Galaxy S',
    model: 'Galaxy S21',
    marketingName: 'Samsung Galaxy S21',
    osMin: '11',
    year: 2021,
    generation: 'S21',
    inches: 6.2,
    logical: [360, 800],
    physical: [1080, 2400],
    dpr: 3,
    ppi: 421,
    bucket: 'xxhdpi',
    statusBar: 28,
    gestureInset: 24,
    cutout: 'punch-hole-center',
    cutoutBox: [24, 24, 10],
    cornerRadius: 20,
    keyboardHeight: 260,
  },
  {
    id: 'samsung-galaxy-s23',
    manufacturer: 'Samsung',
    family: 'Galaxy S',
    model: 'Galaxy S23',
    marketingName: 'Samsung Galaxy S23',
    osMin: '13',
    year: 2023,
    generation: 'S23',
    inches: 6.1,
    logical: [360, 780],
    physical: [1080, 2340],
    dpr: 3,
    ppi: 425,
    bucket: 'xxhdpi',
    statusBar: 28,
    gestureInset: 24,
    cutout: 'punch-hole-center',
    cutoutBox: [24, 24, 10],
    cornerRadius: 20,
    keyboardHeight: 260,
  },
  {
    id: 'samsung-galaxy-s24',
    manufacturer: 'Samsung',
    family: 'Galaxy S',
    model: 'Galaxy S24',
    marketingName: 'Samsung Galaxy S24',
    osMin: '14',
    year: 2024,
    generation: 'S24',
    inches: 6.2,
    logical: [360, 772],
    physical: [1080, 2316],
    dpr: 3,
    ppi: 416,
    bucket: 'xxhdpi',
    statusBar: 28,
    gestureInset: 24,
    cutout: 'punch-hole-center',
    cutoutBox: [24, 24, 10],
    cornerRadius: 20,
    keyboardHeight: 260,
  },
  {
    id: 'samsung-galaxy-s24-ultra',
    manufacturer: 'Samsung',
    family: 'Galaxy S',
    model: 'Galaxy S24 Ultra',
    marketingName: 'Samsung Galaxy S24 Ultra',
    osMin: '14',
    year: 2024,
    generation: 'S24',
    inches: 6.8,
    logical: [384, 832],
    physical: [1440, 3120],
    dpr: 3.75,
    ppi: 505,
    bucket: 'xxxhdpi',
    statusBar: 28,
    gestureInset: 24,
    cutout: 'punch-hole-center',
    cutoutBox: [24, 24, 10],
    cornerRadius: 12,
    keyboardHeight: 270,
  },
  {
    id: 'samsung-galaxy-a54',
    manufacturer: 'Samsung',
    family: 'Galaxy A',
    model: 'Galaxy A54',
    marketingName: 'Samsung Galaxy A54 5G',
    osMin: '13',
    year: 2023,
    generation: 'A54',
    inches: 6.4,
    logical: [360, 780],
    physical: [1080, 2340],
    dpr: 3,
    ppi: 403,
    bucket: 'xxhdpi',
    statusBar: 28,
    gestureInset: 24,
    cutout: 'teardrop',
    cutoutBox: [22, 22, 8],
    cornerRadius: 18,
    keyboardHeight: 260,
  },
  {
    id: 'oneplus-11',
    manufacturer: 'OnePlus',
    family: 'OnePlus',
    model: 'OnePlus 11',
    marketingName: 'OnePlus 11',
    osMin: '13',
    year: 2023,
    generation: '11',
    inches: 6.7,
    logical: [412, 919],
    physical: [1440, 3216],
    dpr: 3.5,
    ppi: 525,
    bucket: 'xxxhdpi',
    statusBar: 24,
    gestureInset: 24,
    cutout: 'punch-hole-left',
    cutoutBox: [26, 26, 12],
    cornerRadius: 26,
    keyboardHeight: 270,
  },
  {
    id: 'xiaomi-13',
    manufacturer: 'Xiaomi',
    family: 'Xiaomi',
    model: 'Xiaomi 13',
    marketingName: 'Xiaomi 13',
    osMin: '13',
    year: 2023,
    generation: '13',
    inches: 6.36,
    logical: [393, 873],
    physical: [1080, 2400],
    dpr: 2.75,
    ppi: 414,
    bucket: 'xxhdpi',
    statusBar: 27,
    gestureInset: 24,
    cutout: 'punch-hole-center',
    cutoutBox: [24, 24, 10],
    cornerRadius: 18,
    keyboardHeight: 265,
  },
  {
    id: 'nothing-phone-2',
    manufacturer: 'Nothing',
    family: 'Phone',
    model: 'Phone (2)',
    marketingName: 'Nothing Phone (2)',
    osMin: '13',
    year: 2023,
    generation: '2',
    inches: 6.7,
    logical: [412, 919],
    physical: [1080, 2412],
    dpr: 2.625,
    ppi: 394,
    bucket: 'xxhdpi',
    statusBar: 24,
    gestureInset: 24,
    cutout: 'punch-hole-center',
    cutoutBox: [26, 26, 10],
    cornerRadius: 26,
    keyboardHeight: 275,
  },
  {
    id: 'motorola-moto-g-power-2022',
    manufacturer: 'Motorola',
    family: 'Moto G',
    model: 'Moto G Power (2022)',
    marketingName: 'Motorola Moto G Power (2022)',
    osMin: '11',
    year: 2022,
    generation: 'G Power',
    inches: 6.5,
    logical: [360, 800],
    physical: [720, 1600],
    dpr: 2,
    ppi: 269,
    bucket: 'hdpi',
    statusBar: 24,
    gestureInset: 24,
    cutout: 'teardrop',
    cutoutBox: [20, 20, 6],
    cornerRadius: 12,
    keyboardHeight: 250,
  },
];

const INSET_CAVEAT =
  'Android window insets depend on OEM skin, OS version and the user\'s navigation setting; treat these values as representative defaults rather than guarantees.';

function toRaw(spec: AndroidSpec, navMode: 'android-gesture' | 'android-three-button'): RawDeviceRecord {
  const [w, h] = spec.logical;
  const gesture = navMode === 'android-gesture';
  const bottomInset = gesture ? spec.gestureInset : 48;
  return {
    id: gesture ? spec.id : `${spec.id}-3button`,
    manufacturer: spec.manufacturer,
    family: spec.family,
    model: spec.model,
    marketingName: gesture ? spec.marketingName : `${spec.marketingName} (3-button nav)`,
    platform: 'android',
    osName: 'Android',
    osMin: spec.osMin,
    releaseYear: spec.year,
    generation: spec.generation,
    screenSizeInches: spec.inches,

    logicalWidth: w,
    logicalHeight: h,
    physicalWidth: spec.physical[0],
    physicalHeight: spec.physical[1],
    devicePixelRatio: spec.dpr,
    ppi: spec.ppi,
    densityBucket: spec.bucket,

    safeTop: spec.statusBar,
    safeBottom: bottomInset,
    safeLeft: 0,
    safeRight: 0,
    statusBarHeight: spec.statusBar,
    statusBarOverlaysContent: true,

    cutoutKind: spec.cutout,
    cutoutWidth: spec.cutoutBox[0],
    cutoutHeight: spec.cutoutBox[1],
    cutoutTop: spec.cutoutBox[2],
    cutoutRadius: spec.cutoutBox[0] / 2,

    navMode,
    navHeight: bottomInset,
    indicatorWidth: gesture ? 108 : 0,

    screenCornerRadius: spec.cornerRadius,

    keyboardSupported: true,
    keyboardHeight: spec.keyboardHeight,
    keyboardAccessoryHeight: 0,

    landscape: {
      width: h,
      height: w,
      safeTop: 0,
      safeBottom: gesture ? 16 : 48,
      safeLeft: 0,
      safeRight: 0,
    },

    ...ANDROID_CONVENTIONS,

    sources: {
      identity: 'oem-spec',
      viewport: 'oem-spec',
      physical: 'oem-spec',
      safeArea: 'android-docs',
      cutout: 'android-docs',
      navigation: 'android-docs',
      cornerRadius: 'community-dataset',
      keyboard: 'community-dataset',
      conventions: 'android-docs',
    },
    confidence: {
      viewport: 'high',
      physical: 'high',
      safeArea: 'medium',
      cutout: 'medium',
      navigation: 'medium',
      cornerRadius: 'low',
      keyboard: 'low',
    },
    references: {
      safeArea: 'https://developer.android.com/develop/ui/views/layout/edge-to-edge',
      cutout: 'https://developer.android.com/develop/ui/views/layout/display-cutout',
      navigation: 'https://developer.android.com/develop/ui/views/layout/insets',
      conventions: 'https://m3.material.io/foundations/layout/understanding-layout/overview',
    },
    caveats: [
      INSET_CAVEAT,
      'Software keyboard height varies by IME (Gboard, Samsung Keyboard, ...); the catalog value is a representative Gboard portrait height.',
    ],
  };
}

export const androidProvider: DeviceDataProvider = {
  id: 'android',
  name: 'Android developer documentation + OEM specifications',
  url: 'https://developer.android.com/develop/ui/views/layout/insets',
  license: 'Referenced documentation; no data files redistributed.',
  precedence: 90,
  fetch: () => [
    ...PHONES.map((spec) => toRaw(spec, 'android-gesture')),
    // A three-button-navigation variant for the two most common test targets,
    // since the 48dp bottom inset materially changes bottom-bar clearance.
    toRaw(PHONES[1]!, 'android-three-button'),
    toRaw(PHONES[9]!, 'android-three-button'),
  ],
};
