import type { DeviceDataProvider, RawDeviceRecord } from '../schema/raw.js';

/**
 * Apple device geometry.
 *
 * Viewport, physical resolution, DPR and PPI come from Apple's published
 * technical specifications. Safe-area insets, status-bar heights and the home
 * indicator follow the layout guidance in the Human Interface Guidelines and
 * the documented UIKit safe-area behaviour.
 *
 * Display corner radii are NOT published by Apple. They are carried at
 * `medium`/`low` confidence from a normalised community measurement and are
 * used only by the cosmetic device-shell layer, never by adaptation geometry.
 */

const IOS_CONVENTIONS = {
  minTouchTarget: 44,
  defaultScreenMargin: 16,
  bottomTabBarHeight: 49,
  systemFont: 'SF Pro Text',
} as const;

interface IPhoneSpec {
  id: string;
  marketingName: string;
  model: string;
  generation: string;
  year: number;
  inches: number;
  osMin: string;
  logical: [number, number];
  physical: [number, number];
  dpr: number;
  ppi: number;
  safeTop: number;
  safeBottom: number;
  statusBar: number;
  cutout: RawDeviceRecord['cutoutKind'];
  cutoutBox: [number, number, number]; // width, height, top
  cornerRadius: number;
  cornerRadiusConfidence?: 'medium' | 'low';
  keyboardHeight: number;
  geometryConfidence?: 'high' | 'medium' | 'low';
  caveats?: string[];
}

const NOTCH: [number, number, number] = [209, 30, 0];
const NOTCH_MINI: [number, number, number] = [180, 30, 0];
const ISLAND: [number, number, number] = [125, 37, 11];

const IPHONES: IPhoneSpec[] = [
  {
    id: 'apple-iphone-se-3',
    marketingName: 'iPhone SE (3rd generation)',
    model: 'iPhone SE 3',
    generation: '2022',
    year: 2022,
    inches: 4.7,
    osMin: '15.4',
    logical: [375, 667],
    physical: [750, 1334],
    dpr: 2,
    ppi: 326,
    safeTop: 20,
    safeBottom: 0,
    statusBar: 20,
    cutout: 'none',
    cutoutBox: [0, 0, 0],
    cornerRadius: 0,
    keyboardHeight: 216,
  },
  {
    id: 'apple-iphone-13-mini',
    marketingName: 'iPhone 13 mini',
    model: 'iPhone 13 mini',
    generation: '13',
    year: 2021,
    inches: 5.4,
    osMin: '15.0',
    logical: [375, 812],
    physical: [1125, 2436],
    dpr: 3,
    ppi: 476,
    safeTop: 50,
    safeBottom: 34,
    statusBar: 50,
    cutout: 'notch',
    cutoutBox: NOTCH_MINI,
    cornerRadius: 44,
    cornerRadiusConfidence: 'medium',
    keyboardHeight: 291,
  },
  {
    id: 'apple-iphone-13',
    marketingName: 'iPhone 13',
    model: 'iPhone 13',
    generation: '13',
    year: 2021,
    inches: 6.1,
    osMin: '15.0',
    logical: [390, 844],
    physical: [1170, 2532],
    dpr: 3,
    ppi: 460,
    safeTop: 47,
    safeBottom: 34,
    statusBar: 47,
    cutout: 'notch',
    cutoutBox: NOTCH,
    cornerRadius: 47,
    cornerRadiusConfidence: 'medium',
    keyboardHeight: 291,
  },
  {
    id: 'apple-iphone-14',
    marketingName: 'iPhone 14',
    model: 'iPhone 14',
    generation: '14',
    year: 2022,
    inches: 6.1,
    osMin: '16.0',
    logical: [390, 844],
    physical: [1170, 2532],
    dpr: 3,
    ppi: 460,
    safeTop: 47,
    safeBottom: 34,
    statusBar: 47,
    cutout: 'notch',
    cutoutBox: NOTCH,
    cornerRadius: 47,
    cornerRadiusConfidence: 'medium',
    keyboardHeight: 291,
  },
  {
    id: 'apple-iphone-14-plus',
    marketingName: 'iPhone 14 Plus',
    model: 'iPhone 14 Plus',
    generation: '14',
    year: 2022,
    inches: 6.7,
    osMin: '16.0',
    logical: [428, 926],
    physical: [1284, 2778],
    dpr: 3,
    ppi: 458,
    safeTop: 47,
    safeBottom: 34,
    statusBar: 47,
    cutout: 'notch',
    cutoutBox: NOTCH,
    cornerRadius: 53,
    cornerRadiusConfidence: 'medium',
    keyboardHeight: 302,
  },
  {
    id: 'apple-iphone-14-pro',
    marketingName: 'iPhone 14 Pro',
    model: 'iPhone 14 Pro',
    generation: '14',
    year: 2022,
    inches: 6.1,
    osMin: '16.0',
    logical: [393, 852],
    physical: [1179, 2556],
    dpr: 3,
    ppi: 460,
    safeTop: 59,
    safeBottom: 34,
    statusBar: 54,
    cutout: 'dynamic-island',
    cutoutBox: ISLAND,
    cornerRadius: 55,
    cornerRadiusConfidence: 'medium',
    keyboardHeight: 291,
  },
  {
    id: 'apple-iphone-15',
    marketingName: 'iPhone 15',
    model: 'iPhone 15',
    generation: '15',
    year: 2023,
    inches: 6.1,
    osMin: '17.0',
    logical: [393, 852],
    physical: [1179, 2556],
    dpr: 3,
    ppi: 461,
    safeTop: 59,
    safeBottom: 34,
    statusBar: 54,
    cutout: 'dynamic-island',
    cutoutBox: ISLAND,
    cornerRadius: 55,
    cornerRadiusConfidence: 'medium',
    keyboardHeight: 291,
  },
  {
    id: 'apple-iphone-15-pro-max',
    marketingName: 'iPhone 15 Pro Max',
    model: 'iPhone 15 Pro Max',
    generation: '15',
    year: 2023,
    inches: 6.7,
    osMin: '17.0',
    logical: [430, 932],
    physical: [1290, 2796],
    dpr: 3,
    ppi: 460,
    safeTop: 59,
    safeBottom: 34,
    statusBar: 54,
    cutout: 'dynamic-island',
    cutoutBox: ISLAND,
    cornerRadius: 55,
    cornerRadiusConfidence: 'medium',
    keyboardHeight: 302,
  },
  {
    id: 'apple-iphone-16',
    marketingName: 'iPhone 16',
    model: 'iPhone 16',
    generation: '16',
    year: 2024,
    inches: 6.1,
    osMin: '18.0',
    logical: [393, 852],
    physical: [1179, 2556],
    dpr: 3,
    ppi: 460,
    safeTop: 59,
    safeBottom: 34,
    statusBar: 54,
    cutout: 'dynamic-island',
    cutoutBox: ISLAND,
    cornerRadius: 55,
    cornerRadiusConfidence: 'medium',
    keyboardHeight: 291,
  },
  {
    id: 'apple-iphone-16-pro',
    marketingName: 'iPhone 16 Pro',
    model: 'iPhone 16 Pro',
    generation: '16',
    year: 2024,
    inches: 6.3,
    osMin: '18.0',
    logical: [402, 874],
    physical: [1206, 2622],
    dpr: 3,
    ppi: 460,
    safeTop: 62,
    safeBottom: 34,
    statusBar: 54,
    cutout: 'dynamic-island',
    cutoutBox: ISLAND,
    cornerRadius: 62,
    cornerRadiusConfidence: 'medium',
    keyboardHeight: 291,
  },
  {
    id: 'apple-iphone-16-pro-max',
    marketingName: 'iPhone 16 Pro Max',
    model: 'iPhone 16 Pro Max',
    generation: '16',
    year: 2024,
    inches: 6.9,
    osMin: '18.0',
    logical: [440, 956],
    physical: [1320, 2868],
    dpr: 3,
    ppi: 460,
    safeTop: 62,
    safeBottom: 34,
    statusBar: 54,
    cutout: 'dynamic-island',
    cutoutBox: ISLAND,
    cornerRadius: 62,
    cornerRadiusConfidence: 'medium',
    keyboardHeight: 302,
  },
  {
    id: 'apple-iphone-16e',
    marketingName: 'iPhone 16e',
    model: 'iPhone 16e',
    generation: '16',
    year: 2025,
    inches: 6.1,
    osMin: '18.3',
    logical: [390, 844],
    physical: [1170, 2532],
    dpr: 3,
    ppi: 460,
    safeTop: 47,
    safeBottom: 34,
    statusBar: 47,
    cutout: 'notch',
    cutoutBox: NOTCH,
    cornerRadius: 47,
    cornerRadiusConfidence: 'medium',
    keyboardHeight: 291,
  },
  {
    id: 'apple-iphone-17',
    marketingName: 'iPhone 17',
    model: 'iPhone 17',
    generation: '17',
    year: 2025,
    inches: 6.3,
    osMin: '26.0',
    logical: [402, 874],
    physical: [1206, 2622],
    dpr: 3,
    ppi: 460,
    safeTop: 62,
    safeBottom: 34,
    statusBar: 54,
    cutout: 'dynamic-island',
    cutoutBox: ISLAND,
    cornerRadius: 62,
    cornerRadiusConfidence: 'low',
    keyboardHeight: 291,
    geometryConfidence: 'medium',
    caveats: [
      'Safe-area and corner-radius values follow the 6.3-inch Pro geometry introduced with iPhone 16 Pro and have not been re-measured on hardware.',
    ],
  },
  {
    id: 'apple-iphone-17-pro',
    marketingName: 'iPhone 17 Pro',
    model: 'iPhone 17 Pro',
    generation: '17',
    year: 2025,
    inches: 6.3,
    osMin: '26.0',
    logical: [402, 874],
    physical: [1206, 2622],
    dpr: 3,
    ppi: 460,
    safeTop: 62,
    safeBottom: 34,
    statusBar: 54,
    cutout: 'dynamic-island',
    cutoutBox: ISLAND,
    cornerRadius: 62,
    cornerRadiusConfidence: 'low',
    keyboardHeight: 291,
    geometryConfidence: 'medium',
    caveats: ['Layout metrics inherited from the 6.3-inch Pro geometry; not re-measured on hardware.'],
  },
  {
    id: 'apple-iphone-17-pro-max',
    marketingName: 'iPhone 17 Pro Max',
    model: 'iPhone 17 Pro Max',
    generation: '17',
    year: 2025,
    inches: 6.9,
    osMin: '26.0',
    logical: [440, 956],
    physical: [1320, 2868],
    dpr: 3,
    ppi: 460,
    safeTop: 62,
    safeBottom: 34,
    statusBar: 54,
    cutout: 'dynamic-island',
    cutoutBox: ISLAND,
    cornerRadius: 62,
    cornerRadiusConfidence: 'low',
    keyboardHeight: 302,
    geometryConfidence: 'medium',
    caveats: ['Layout metrics inherited from the 6.9-inch Pro Max geometry; not re-measured on hardware.'],
  },
];

function toRaw(spec: IPhoneSpec): RawDeviceRecord {
  const hasHomeButton = spec.cutout === 'none';
  const [w, h] = spec.logical;
  const geometryConfidence = spec.geometryConfidence ?? 'high';
  return {
    id: spec.id,
    manufacturer: 'Apple',
    family: 'iPhone',
    model: spec.model,
    marketingName: spec.marketingName,
    platform: 'ios',
    osName: 'iOS',
    osMin: spec.osMin,
    releaseYear: spec.year,
    generation: spec.generation,
    screenSizeInches: spec.inches,

    logicalWidth: w,
    logicalHeight: h,
    physicalWidth: spec.physical[0],
    physicalHeight: spec.physical[1],
    devicePixelRatio: spec.dpr,
    ppi: spec.ppi,

    safeTop: spec.safeTop,
    safeBottom: spec.safeBottom,
    safeLeft: 0,
    safeRight: 0,
    statusBarHeight: spec.statusBar,
    statusBarOverlaysContent: true,

    cutoutKind: spec.cutout,
    cutoutWidth: spec.cutoutBox[0],
    cutoutHeight: spec.cutoutBox[1],
    cutoutTop: spec.cutoutBox[2],
    cutoutRadius: spec.cutout === 'dynamic-island' ? spec.cutoutBox[1] / 2 : 20,

    navMode: hasHomeButton ? 'ios-home-button' : 'ios-home-indicator',
    navHeight: hasHomeButton ? 0 : 34,
    indicatorWidth: hasHomeButton ? 0 : 139,

    screenCornerRadius: spec.cornerRadius,

    keyboardSupported: true,
    keyboardHeight: spec.keyboardHeight,
    keyboardAccessoryHeight: 44,

    landscape: {
      width: h,
      height: w,
      safeTop: 0,
      safeBottom: hasHomeButton ? 0 : 21,
      safeLeft: hasHomeButton ? 0 : spec.safeTop,
      safeRight: hasHomeButton ? 0 : spec.safeTop,
    },

    ...IOS_CONVENTIONS,

    sources: {
      identity: 'apple-tech-specs',
      viewport: 'apple-tech-specs',
      physical: 'apple-tech-specs',
      safeArea: 'apple-hig',
      cutout: 'apple-hig',
      navigation: 'apple-hig',
      cornerRadius: 'community-dataset',
      keyboard: 'apple-hig',
      conventions: 'apple-hig',
    },
    confidence: {
      viewport: geometryConfidence,
      physical: geometryConfidence,
      safeArea: geometryConfidence,
      cutout: geometryConfidence,
      cornerRadius: spec.cornerRadiusConfidence ?? 'medium',
      keyboard: 'medium',
    },
    references: {
      identity: 'https://support.apple.com/specs/iphone',
      viewport: 'https://developer.apple.com/design/human-interface-guidelines/layout',
      safeArea: 'https://developer.apple.com/design/human-interface-guidelines/layout',
      cutout: 'https://developer.apple.com/design/human-interface-guidelines/the-dynamic-island',
      cornerRadius: 'Normalised community measurement of UIScreen._displayCornerRadius',
    },
    caveats: [
      ...(spec.caveats ?? []),
      'Keyboard height varies with language, predictive bar and hardware keyboard state; the catalog value is the default English portrait keyboard.',
    ],
  };
}

export const appleProvider: DeviceDataProvider = {
  id: 'apple',
  name: 'Apple technical specifications + Human Interface Guidelines',
  url: 'https://developer.apple.com/design/human-interface-guidelines/',
  license: 'Referenced documentation; no data files redistributed.',
  precedence: 100,
  fetch: () => IPHONES.map(toRaw),
};
