import { createHmac, timingSafeEqual } from 'node:crypto';
import { mkdir, readFile, writeFile, stat } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { Injectable, Logger } from '@nestjs/common';
import { loadEnv } from '../config/env.js';

export interface StoredAsset {
  id: string;
  mimeType: string;
  byteSize: number;
}

export const ASSET_STORE = 'ASSET_STORE';

export interface AssetStore {
  put(id: string, data: Buffer, mimeType: string): Promise<StoredAsset>;
  get(id: string): Promise<Buffer | undefined>;
  has(id: string): boolean;
  /** Time-limited URL. Never a raw filesystem path (spec section 27). */
  signedUrl(id: string): string;
  verify(id: string, expires: string, signature: string): boolean;
}

/**
 * Local-disk asset store.
 *
 * Assets are addressed by opaque id only - filenames from the upload never
 * reach the filesystem - and served through a signed, expiring URL so an
 * uploaded design cannot be enumerated or hot-linked.
 */
@Injectable()
export class LocalAssetStore implements AssetStore {
  private readonly logger = new Logger(LocalAssetStore.name);
  private readonly dir = resolve(loadEnv().ASSET_DIR);
  private readonly secret = loadEnv().ASSET_URL_SECRET;
  private readonly ttl = loadEnv().ASSET_URL_TTL_SECONDS;
  private readonly types = new Map<string, string>();

  private path(id: string): string {
    // The id is generated by us and validated here, so no user-controlled
    // segment can ever escape the asset directory.
    if (!/^[A-Za-z0-9_-]{1,64}$/.test(id)) throw new Error(`Invalid asset id: ${id}`);
    return join(this.dir, id);
  }

  async put(id: string, data: Buffer, mimeType: string): Promise<StoredAsset> {
    await mkdir(this.dir, { recursive: true });
    const target = this.path(id);
    await writeFile(target, data);
    await writeFile(`${target}.meta.json`, JSON.stringify({ mimeType, byteSize: data.byteLength }), 'utf8');
    this.types.set(id, mimeType);
    this.logger.debug(`Stored asset ${id} (${data.byteLength} bytes)`);
    return { id, mimeType, byteSize: data.byteLength };
  }

  async get(id: string): Promise<Buffer | undefined> {
    try {
      return await readFile(this.path(id));
    } catch {
      return undefined;
    }
  }

  async mimeType(id: string): Promise<string> {
    const cached = this.types.get(id);
    if (cached) return cached;
    try {
      const meta = JSON.parse(await readFile(`${this.path(id)}.meta.json`, 'utf8')) as { mimeType: string };
      this.types.set(id, meta.mimeType);
      return meta.mimeType;
    } catch {
      return 'application/octet-stream';
    }
  }

  async byteSize(id: string): Promise<number> {
    try {
      return (await stat(this.path(id))).size;
    } catch {
      return 0;
    }
  }

  has(id: string): boolean {
    try {
      return existsSync(this.path(id));
    } catch {
      return false;
    }
  }

  signedUrl(id: string): string {
    const expires = String(Math.floor(Date.now() / 1000) + this.ttl);
    const signature = this.sign(id, expires);
    return `/assets/${id}?expires=${expires}&signature=${signature}`;
  }

  verify(id: string, expires: string, signature: string): boolean {
    if (!/^\d+$/.test(expires)) return false;
    if (Number(expires) * 1000 < Date.now()) return false;
    const expected = Buffer.from(this.sign(id, expires));
    const provided = Buffer.from(signature);
    if (expected.length !== provided.length) return false;
    return timingSafeEqual(expected, provided);
  }

  private sign(id: string, expires: string): string {
    return createHmac('sha256', this.secret).update(`${id}:${expires}`).digest('hex');
  }
}
